package me.roxo.netherbingo.managers;

public enum ItemsOfAchievement {

    DIAMOND_HORSE_ARMOR, WITHER_SKELETON_SKULL, JUKEBOX, RED_NETHER_BRICKS, COAL_BLOCK, EYE_OF_ENDER, SNOUT_BANNER_PATTERN, PIGSTEP, GILDED_BLACKSTONE, LODESTONE, RESPAWN_ANCHOR, SOUL_SPEED_3_BOOK, WATER_BUCKET, GOLDEN_APPLE, ANVIL, SOUL_LANTERN, IRON_BLOCK, SMOOTH_BASALT, BANNER, GHAST_TEAR, ROTTEN_FLESH, SMOKER, NETHERITE_INGOT, WHITE_LEATHER_HORSE_ARMOR, WARPED_NYLIUM, TRAPPED_CHEST, QUARTZ_BRICKS



}
